### ISSUE TITLE
Publish on NPM registry to have link to GitHub repository

### ISSUE THREAD

**Issue by madarche** [jnordberg/browsernizr#11]
Hello @jnordberg,

Could you publish browsernizr again on NPM registry so that https://www.npmjs.com/package/browsernizr has the link to this GitHub repository please?

This is related to #10.

Thanks!

**Comment by jmagnusson** [comment]
Would love to see this as well.

**Comment by jnordberg** [comment]
Done

**Comment by madarche** [comment]
@jnordberg Thanks! :-)
