### ISSUE TITLE
New update from Modernizr repo

### ISSUE THREAD

**Issue by laustdeleuran** [jnordberg/browsernizr#15]
Is there any chance we can get a new pull from the current Modernizr repo? It's been a while :)

Thanks!

**Comment by aldendaniels** [comment]
+1 Would definately use browsernizr if it stayed up-to-date with modernizr.

**Comment by aldendaniels** [comment]
Created PR #16 to do this.

**Comment by isellsoap** [comment]
*knock* *knock* Somebody here? 

Would love to see this merged!

**Comment by nicholascloud** [comment]
:+1: for merge

**Comment by jnordberg** [comment]
Merged

**Comment by jnordberg** [comment]
Published as 1.1.0 on npm

**Comment by nicholascloud** [comment]
@jnordberg Awesome, thanks!
