### ISSUE TITLE
Consider using nodefy

### ISSUE THREAD

**Issue by aldendaniels** [jnordberg/browsernizr#17]
@jnordberg - looks like you're using a custom-built AMD -> CommonJS converter. 

In case it proves useful - checkout @millermedeiros's [nodefy](https://github.com/millermedeiros/nodefy) project.

**Comment by jmagnusson** [comment]
Already mentioned in #9.

Hmm it's a bit quiet in here... Where are you @jnordberg?

**Comment by jnordberg** [comment]
Hey, i'm a bit busy at the moment. I'll accept a PR ;)
