### ISSUE TITLE
transforms3d.js require supports causes build failure

### ISSUE THREAD

**Issue by ccpotter** [jnordberg/browsernizr#22]
In file transforms3d.js line 5 causes a build failure due to a path location issue.

Error: Cannot find module './../../lib/test/css/supports' from 'C:\Users\USERNAME\git\PROJECT\node_modules\browsernizr\test\css'

PROBLEM LINE: 5: require('./../../lib/test/css/supports');

SOLUTION LINE 5: require('./supports');

**Comment by ascii-husky** [comment]
+1

**Comment by jnordberg** [comment]
Fixed in 2.0.0
