### ISSUE TITLE
css/filter - Uncaught TypeError: prefixes.join is not a function

### ISSUE THREAD

**Issue by patlux** [jnordberg/browsernizr#23]
https://github.com/jnordberg/browsernizr/blob/master/test/css/filters.js

```js
var testAllProps = require('./../../lib/prefixes.js');
var prefixes = require('./../../lib/testAllProps.js');
```

I think it has to be

```js
var testAllProps = require('./../../lib/testAllProps.js');
var prefixes = require('./../../lib/prefixes.js');
```

I'm the only one who needs this test? :D

**Comment by jnordberg** [comment]
That's really odd, must have some bug in the new build script

**Comment by jnordberg** [comment]
Wasn't a problem with the build script... But at least I got it updated for npm 3

Modernizr/Modernizr#1744
