### ISSUE TITLE
Is requiring the full lodash bundle in `generate.js` bloating the outputted code?

### ISSUE THREAD

**Issue by laustdeleuran** [jnordberg/browsernizr#29]
On [line 1 of generate.js](https://github.com/jnordberg/browsernizr/blob/master/lib/generate.js#L1) Browsernizr is importing all of lodash to use four utility functions. Is this code being put in the bundle Browsernizr creates, and if so, blaoting the end result for all users? 

It would be fairly easy to just import the utilities that files is using instead. Let me know, and I'll submit a PR.

**Comment by jnordberg** [comment]
That code is never executed unless you require it explicitly

**Comment by laustdeleuran** [comment]
@jnordberg Ah, see that now. Sorry about the confusion! Feel free to close this. 

On more of a curious note, what's the use case for requiring this file explicitly?

**Comment by jnordberg** [comment]
There isn't one, just a byproduct of how Modernizr has their own sort-of-bundler :)
